Repository CS2103-AY1819S1-T12-2/main, pull requests merged in 2018-11, with the labels that each got.

#147 extract strings as static final constant fields
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/PredictCommand.java
  src/test/java/seedu/address/model/DiagnosisModelManagerTest.java
  src/test/java/seedu/address/model/DiagnosisTest.java
  src/test/java/seedu/address/model/symptom/DiseaseTest.java
  src/test/java/seedu/address/model/symptom/SymptomTest.java
Labels: priority.Low

#151 edit the naming of profile pic
  docs/AboutUs.adoc
  docs/images/zzg229.png
Labels: priority.Low

#152 Edit the developer guide
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/Diagnosis.java
Labels: priority.High

#153 add diagram for developer guide
  docs/DeveloperGuide.adoc
  docs/diagrams/DiagnosisSequenceDiagram.pptx
  docs/images/DiagnosisSequenceDiagram.png
  src/main/java/seedu/address/model/Diagnosis.java
Labels: priority.Low

#163 edit the diagnosis related classes
  docs/UserGuide.adoc
  docs/team/ZhouZegang.adoc
  docs/team/johndoe.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/PredictCommand.java
  src/main/java/seedu/address/model/Diagnosis.java
Labels: priority.High

#167 edit the exception message
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: priority.Low

#176 edit the user guide
  docs/UserGuide.adoc
  docs/images/ErrorMessageForWrongAddDiseaseCommand.png
  docs/images/FindDiseaseInfluenza.png
  docs/images/PredictDiseaseValidDemo.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: priority.Medium, type.Bug, type.Enhancement

#178 edit the user guide
  docs/UserGuide.adoc
  docs/images/PredictDiseaseInvalidDemo.png
  docs/images/PredictDiseaseValidDemo.png
  docs/images/PredictInvalidDemo.png
Labels: priority.Low, type.Fix

#177 Minor documentation changes, max length for params implemented
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
Labels: severity.Low, type.Fix

#184 edit the path issue for drug utility
  src/main/java/seedu/address/commons/util/DrugCsvUtil.java
  src/main/java/seedu/address/model/Diagnosis.java
Labels: priority.High, type.Bug

#187 Added PPP, Increased Coverage to 70%
  docs/DeveloperGuide.adoc
  docs/team/quekshuiherng.adoc
  src/test/data/XmlSerializableScheduleTest/duplicateEventSchedule.xml
  src/test/data/XmlSerializableScheduleTest/invalidEventSchedule.xml
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlSerializableScheduleTest.java
  src/test/java/seedu/address/testutil/ScheduleEventUtil.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: TRAVIS, Why don't we have a label for tests

#199 add manual testing cases for diagnosis
  docs/DeveloperGuide.adoc
Labels: type.Task

#201 edit the dg
  docs/DeveloperGuide.adoc
  docs/team/zhouzegang.adoc
Labels: type.Task

#215 rename the ppp file
  docs/AboutUs.adoc
  docs/team/zzg229.adoc
Labels: type.Fix
