Repository CS2103-AY1819S1-T12-2/main, pull requests merged in 2018-10, with the labels that each got.

#12 Added Calendar Methods.
  src/main/java/seedu/address/commons/events/model/CalendarChangedEvent.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/AddressBookModel.java
  src/main/java/seedu/address/model/AddressBookModelManager.java
  src/main/java/seedu/address/model/Calendar.java
  src/main/java/seedu/address/model/CalendarModel.java
  src/main/java/seedu/address/model/CalendarModelManager.java
Labels: enhancement, help wanted

#33 add basic storage functions for disease-symptom storage class
  src/main/java/seedu/address/model/ModelCalendar.java
  src/main/java/seedu/address/storage/DiseaseAndSymptomStorage.java
  src/main/resources/storage/datasetForSymptomAndDisease.csv
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority.High, status.Ongoing, type.Epic, type.Story

#34 Added Storage logic for schedule, modified storage logic for Person t…
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/PatientBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/event/EventID.java
  src/main/java/seedu/address/model/event/ScheduleEvent.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonID.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/ScheduleStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedEvent.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlScheduleStorage.java
  src/main/java/seedu/address/storage/XmlSerializableSchedule.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/patientBookParserTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
Labels: priority.High, type.Enhancement

#40 edit the developer guide for v1.2
  docs/DeveloperGuide.adoc
Labels: priority.High, type.Task

#54 edit the Command interface method
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindSymptomsCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ModeCommand.java
Labels: priority.High, type.Enhancement, type.Fix

#59 Complete implementation for DateTimeParser
  src/main/java/seedu/address/commons/util/Pair.java
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/logic/parser/Prompt.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/test/java/seedu/address/logic/parser/DateTimeParserTest.java
Labels: type.Enhancement

#64 edit the command and parser classes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindSymptomsCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListDiseasesCommand.java
  src/main/java/seedu/address/logic/parser/DiagnosisParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindSymptomsCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/PatientBookParser.java
  src/main/java/seedu/address/model/Diagnosis.java
  src/main/java/seedu/address/model/DiagnosisModel.java
  src/main/java/seedu/address/model/DiagnosisModelManager.java
  src/main/java/seedu/address/model/person/MatchPersonPredicate.java
Labels: priority.High, type.Enhancement, type.Fix, type.Task

#67 Changed ScheduleModelManager#internalGetFromEventList
  src/main/java/seedu/address/model/ScheduleModel.java
  src/main/java/seedu/address/model/ScheduleModelManager.java
Labels: priority.Medium

#70 Refactored EditCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PersonCliSyntax.java
  src/main/java/seedu/address/logic/parser/ScheduleEventCliSyntax.java
  src/main/java/seedu/address/model/AddressBookModel.java
  src/main/java/seedu/address/model/AddressBookModelManager.java
  src/main/java/seedu/address/model/ScheduleModel.java
  src/main/java/seedu/address/model/ScheduleModelManager.java
Labels: priority.High

#78 Fixed several bugs, added functionality
  src/main/java/seedu/address/commons/events/model/AddressBookChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/AddressBookModel.java
  src/main/java/seedu/address/model/AddressBookModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ScheduleModel.java
  src/main/java/seedu/address/model/ScheduleModelManager.java
  src/main/java/seedu/address/model/event/ScheduleEvent.java
  src/main/java/seedu/address/model/event/ScheduleEventMatchesPredicate.java
  src/main/java/seedu/address/model/person/MatchPersonPredicate.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/XmlAdaptedEvent.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ScheduleMainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/PatientBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/ScheduleEventBuilder.java
  src/test/java/seedu/address/testutil/ScheduleEventUtil.java
Labels: severity.High, type.Fix

#81 add predict disease command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/PredictCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/PatientBookParser.java
  src/main/java/seedu/address/logic/parser/PredictCommandParser.java
  src/main/java/seedu/address/model/Diagnosis.java
  src/main/java/seedu/address/model/DiagnosisModel.java
  src/main/java/seedu/address/model/DiagnosisModelManager.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/storage/datasetForSymptomAndDisease.csv
Labels: priority.High, type.Enhancement, type.Story

#90 fix bug in exception and reformat scheduleEvent
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/Prompt.java
  src/main/java/seedu/address/logic/parser/ScheduleEventParser.java
  src/main/java/seedu/address/model/event/ScheduleEvent.java
Labels: priority.High, type.Fix

#91 implement more checks at various prompt stages
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/logic/parser/Prompt.java
  src/main/java/seedu/address/logic/parser/ScheduleEventParser.java
  src/main/java/seedu/address/model/event/ScheduleEvent.java
Labels: priority.High, type.Enhancement, type.Fix

#94 Minor improvements in UI display
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ScheduleMainWindow.java
  src/main/resources/view/AppointmentCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PromptWindow.fxml
  src/main/resources/view/ScheduleMainWindow.fxml
Labels: priority.High, type.Enhancement

#98 edit file read/write for csv file
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/Diagnosis.java
Labels: priority.High, severity.High, type.Bug, type.Fix

#95 implement getDateToString for ScheduleEvent and fix checkStyle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ModeCommand.java
  src/main/java/seedu/address/logic/commands/PredictCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ModeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PatientBookParser.java
  src/main/java/seedu/address/logic/parser/Prompt.java
  src/main/java/seedu/address/logic/parser/ScheduleEventParser.java
  src/main/java/seedu/address/logic/parser/exceptions/PromptException.java
  src/main/java/seedu/address/model/AddressBookModel.java
  src/main/java/seedu/address/model/AddressBookModelManager.java
  src/main/java/seedu/address/model/ScheduleModelManager.java
  src/main/java/seedu/address/model/event/ScheduleEvent.java
  src/main/java/seedu/address/model/event/ScheduleEventMatchesPredicate.java
  src/main/java/seedu/address/model/person/MatchPersonPredicate.java
  src/main/java/seedu/address/storage/XmlScheduleStorage.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/ScheduleMainWindow.java
  src/test/java/seedu/address/logic/parser/ModeCommandParserTest.java
Labels: TRAVIS, priority.High, type.Fix

#99 fix checkstyle for appointment card and person card
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/AppointmentCard.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: TRAVIS

#100 Added Unit Tests for edit
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.Low, type.Task

#101 Added Unit Tests for address book for clear, delete and find.
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableScheduleTest/duplicateEventSchedule.xml
  src/test/data/XmlSerializableScheduleTest/invalidEventSchedule.xml
  src/test/data/XmlSerializableScheduleTest/typicalEventsSchedule.xml
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HistoryCommandTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/address/storage/XmlSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/XmlSerializableScheduleTest.java
  src/test/java/seedu/address/testutil/ScheduleEventUtil.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.Low, type.Task

#104 edit the user guide
  docs/UserGuide.adoc
  docs/images/ErrorMessageForAddingExistingDisease.png
  docs/images/ErrorMessageForWrongAddDiseaseCommand.png
  docs/images/FindDiseaseInfluenza.png
  docs/images/PredictDiseaseValidDemo.png
  docs/images/PredictInvalidDemo.png
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/PredictCommand.java
  src/main/resources/storage/datasetForSymptomAndDisease.csv
Labels: priority.Medium, type.Enhancement, type.Task

#105 Updated user guide for patient mode use
  docs/UserGuide.adoc
Labels: type.Task

#106 Add in image for UG and refactor the schedule into appointment
  docs/UserGuide.adoc
  docs/images/AppointmentMode.PNG
  docs/images/PatientMode.PNG
  src/main/java/seedu/address/commons/events/ui/SwitchToAppointmentEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ModeCommand.java
  src/main/java/seedu/address/ui/AppointmentMainWindow.java
  src/main/java/seedu/address/ui/Ui.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/AppointmentMainWindow.fxml
Labels: type.Enhancement
